//
//  InsightsView.swift
//  HabitGarden
//
//  VG Track 3 — Data & Statistics with SwiftUI Charts
//  Created by Ibrahim Jasim Alsalih on 2026-05-04.
//

import SwiftUI
import SwiftData
import Charts

// The Insights screen — shows charts, stats, and smart insights about the user's habits
struct InsightsView: View {
    @Query private var habits: [Habit]

    // Calculates total completions per day for the last 7 days (used by the bar chart)
    private var last7Days: [DailyCount] {
        let calendar = Calendar.current
        let allCompletions = habits.flatMap { $0.completions }

        return (0..<7).reversed().map { offset in
            let day = calendar.date(byAdding: .day, value: -offset, to: .now)!
            let start = calendar.startOfDay(for: day)
            let count = allCompletions.filter {
                calendar.isDate($0.date, inSameDayAs: start)
            }.count
            return DailyCount(date: start, count: count)
        }
    }
    

    // Total completions across all habits this week
    private var weekTotal: Int {
        last7Days.reduce(0) { $0 + $1.count }
    }

    // Longest current streak across all habits
    private var bestStreak: Int {
        habits
            .map { StreakCalculator.currentStreak(for: $0) }
            .max() ?? 0
    }

    // Smart insights generated by analyzing habit patterns
    private var insights: [SmartInsight] {
        InsightEngine.generate(habits: habits)
    }

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {

                // MARK: Headline cards
                HStack(spacing: 12) {
                    StatCard(
                        title: "This week",
                        value: "\(weekTotal)",
                        subtitle: "completions",
                        symbol: "checkmark.seal.fill",
                        color: .green
                    )
                    StatCard(
                        title: "Best streak",
                        value: "\(bestStreak)",
                        subtitle: "days",
                        symbol: "flame.fill",
                        color: .orange
                    )
                }

                // MARK: 7-day bar chart
                VStack(alignment: .leading, spacing: 8) {
                    Text("Last 7 days")
                        .font(.headline)
                    Chart(last7Days) { item in
                        BarMark(
                            x: .value("Day", item.date, unit: .day),
                            y: .value("Completed", item.count)
                        )
                        .foregroundStyle(.green.gradient)
                        .cornerRadius(6)
                    }
                    .chartXAxis {
                        AxisMarks(values: .stride(by: .day)) { value in
                            AxisValueLabel(format: .dateTime.weekday(.abbreviated))
                        }
                    }
                    .frame(height: 220)
                }

                // MARK: Smart Insights
                if !insights.isEmpty {
                    VStack(alignment: .leading, spacing: 12) {
                        HStack {
                            Image(systemName: "sparkles")
                                .foregroundStyle(.purple)
                            Text("Smart insights")
                                .font(.headline)
                        }
                        ForEach(insights) { insight in
                            InsightCard(insight: insight)
                        }
                    }
                }

                // MARK: Per-habit streaks
                VStack(alignment: .leading, spacing: 12) {
                    Text("Streaks per habit")
                        .font(.headline)

                    if habits.isEmpty {
                        Text("Add a habit to see your stats here.")
                            .foregroundStyle(.secondary)
                    } else {
                        ForEach(habits) { habit in
                            HStack {
                                Text(habit.emoji)
                                    .font(.title3)
                                Text(habit.name)
                                Spacer()
                                Label(
                                    "\(StreakCalculator.currentStreak(for: habit))",
                                    systemImage: "flame.fill"
                                )
                                .foregroundStyle(.orange)
                                .font(.subheadline.bold())
                            }
                            .padding(.vertical, 4)
                            Divider()
                        }
                    }
                }
            }
            .padding()
        }
        .navigationTitle("Insights")
        .navigationBarTitleDisplayMode(.inline)
    }
}

// MARK: - Helpers

/// One day worth of completion data, used as the Chart data type.
private struct DailyCount: Identifiable {
    var id: Date { date }
    let date: Date
    let count: Int
}

/// One smart-insight row. Handles both SF Symbol names and emoji symbols.
private struct InsightCard: View {
    let insight: SmartInsight

    /// True if the symbol string is an emoji rather than an SF Symbol name.
    private var symbolIsEmoji: Bool {
        guard let first = insight.symbol.unicodeScalars.first else { return false }
        return first.value > 127
    }

    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            Group {
                if symbolIsEmoji {
                    Text(insight.symbol).font(.title2)
                } else {
                    Image(systemName: insight.symbol)
                        .font(.title2)
                        .foregroundStyle(insight.color)
                }
            }
            .frame(width: 36, height: 36)
            .background(insight.color.opacity(0.15))
            .clipShape(Circle())

            VStack(alignment: .leading, spacing: 4) {
                Text(insight.title)
                    .font(.subheadline.bold())
                Text(insight.message)
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
            Spacer()
        }
        .padding()
        .background(
            RoundedRectangle(cornerRadius: 14)
                .fill(Color(.secondarySystemBackground))
        )
    }
}

/// A small reusable card for top-level stats.
private struct StatCard: View {
    let title: String
    let value: String
    let subtitle: String
    let symbol: String
    let color: Color

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            Label(title, systemImage: symbol)
                .font(.caption)
                .foregroundStyle(color)
            Text(value)
                .font(.system(size: 36, weight: .bold, design: .rounded))
            Text(subtitle)
                .font(.caption)
                .foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding()
        .background(color.opacity(0.12))
        .clipShape(RoundedRectangle(cornerRadius: 16))
    }
}

#Preview {
    NavigationStack {
        InsightsView()
    }
    .modelContainer(for: [Habit.self, HabitCompletion.self], inMemory: true)
}
