//
//  InsightsView.swift
//  HabitGarden
//
//  VG Track 3 — Data & Statistics with SwiftUI Charts
//

import SwiftUI
import SwiftData
import Charts

// The Insights screen — shows charts, stats, and smart insights about the user's habits
struct InsightsView: View {
    @Environment(AuthViewModel.self) private var auth
    @Environment(\.dismiss) private var dismiss
    @Query private var habits: [Habit]

    // Only this account's habits — keeps stats and insights private per user
    private var userHabits: [Habit] {
        guard let userId = auth.currentUser?.id else { return [] }
        return habits.filter { $0.userId == userId }
    }

    // Calculates total completions per day for the last 7 days (used by the bar chart)
    private var last7Days: [DailyCount] {
        let calendar = Calendar.current
        let allCompletions = userHabits.flatMap { $0.completions }

        return (0..<7).reversed().map { offset in
            let day = calendar.date(byAdding: .day, value: -offset, to: .now)!
            let start = calendar.startOfDay(for: day)
            let count = allCompletions.filter {
                calendar.isDate($0.date, inSameDayAs: start)
            }.count
            return DailyCount(date: start, count: count)
        }
    }

    // Total completions across all habits this week
    private var weekTotal: Int {
        last7Days.reduce(0) { $0 + $1.count }
    }

    // Longest current streak across all habits
    private var bestStreak: Int {
        userHabits
            .map { StreakCalculator.currentStreak(for: $0) }
            .max() ?? 0
    }

    // Smart insights generated by analyzing habit patterns
    private var insights: [SmartInsight] {
        InsightEngine.generate(habits: userHabits)
    }

    var body: some View {
        ZStack {
            BaseplateBackground()

            ScrollView {
                VStack(alignment: .leading, spacing: 22) {
                    topBar

                    // MARK: Headline cards
                    HStack(spacing: 12) {
                        BrickStatCard(
                            title: "This week",
                            value: "\(weekTotal)",
                            subtitle: "completions",
                            symbol: "checkmark.seal.fill",
                            tint: Brick.green
                        )
                        BrickStatCard(
                            title: "Best streak",
                            value: "\(bestStreak)",
                            subtitle: "days",
                            symbol: "flame.fill",
                            tint: Brick.red
                        )
                    }

                    // MARK: 7-day bar chart
                    VStack(alignment: .leading, spacing: 10) {
                        Text("Last 7 days").font(.brickHeading(17)).foregroundStyle(Brick.ink)
                        Chart(last7Days) { item in
                            BarMark(
                                x: .value("Day", item.date, unit: .day),
                                y: .value("Completed", item.count)
                            )
                            .foregroundStyle(Brick.blue)
                            .cornerRadius(6)
                        }
                        .chartXAxis {
                            AxisMarks(values: .stride(by: .day)) { value in
                                AxisValueLabel(format: .dateTime.weekday(.abbreviated))
                            }
                        }
                        .frame(height: 200)
                    }
                    .padding(16)
                    .brickCard(fill: Brick.white, cornerRadius: 18, borderWidth: 2.5, shadowOffset: 4)

                    // MARK: Smart Insights
                    if !insights.isEmpty {
                        VStack(alignment: .leading, spacing: 12) {
                            HStack(spacing: 6) {
                                Image(systemName: "sparkles").foregroundStyle(Brick.purple)
                                Text("Smart insights").font(.brickHeading(17)).foregroundStyle(Brick.ink)
                            }
                            ForEach(insights) { insight in
                                BrickInsightCard(insight: insight)
                            }
                        }
                    }

                    // MARK: Per-habit streaks
                    VStack(alignment: .leading, spacing: 12) {
                        Text("Streaks per habit").font(.brickHeading(17)).foregroundStyle(Brick.ink)

                        if userHabits.isEmpty {
                            Text("Add a habit to see your stats here.")
                                .font(.brickBody(14))
                                .foregroundStyle(Brick.ink.opacity(0.6))
                        } else {
                            VStack(spacing: 10) {
                                ForEach(userHabits) { habit in
                                    HStack {
                                        Text(habit.emoji.isEmpty ? "🌱" : habit.emoji).font(.title3)
                                        Text(habit.name).font(.brickBody(15)).foregroundStyle(Brick.ink)
                                        Spacer()
                                        Text("🔥 \(StreakCalculator.currentStreak(for: habit))")
                                            .font(.brickBodyHeavy(14))
                                            .foregroundStyle(Brick.ink)
                                    }
                                    .padding(.horizontal, 14)
                                    .padding(.vertical, 10)
                                    .brickCard(fill: Brick.cream, cornerRadius: 14, borderWidth: 2, shadowOffset: 3)
                                }
                            }
                        }
                    }
                }
                .padding(20)
            }
        }
        .navigationBarTitleDisplayMode(.inline)
        .toolbar(.hidden, for: .navigationBar)
    }

    private var topBar: some View {
        HStack(spacing: 14) {
            Button { dismiss() } label: {
                Image(systemName: "chevron.left")
                    .font(.system(size: 15, weight: .bold))
                    .foregroundStyle(Brick.ink)
                    .frame(width: 38, height: 38)
                    .background(Circle().fill(Brick.white))
                    .overlay(Circle().stroke(Brick.ink, lineWidth: 2.5))
                    .compositingGroup()
                    .shadow(color: Brick.ink, radius: 0, x: 3, y: 3)
            }
            Text("Insights").font(.brickTitle(26)).foregroundStyle(Brick.ink)
            Spacer()
        }
        .padding(.top, 4)
    }
}

// MARK: - Helpers

/// One day worth of completion data, used as the Chart data type.
private struct DailyCount: Identifiable {
    var id: Date { date }
    let date: Date
    let count: Int
}

/// One smart-insight row. Handles both SF Symbol names and emoji symbols.
private struct BrickInsightCard: View {
    let insight: SmartInsight

    /// True if the symbol string is an emoji rather than an SF Symbol name.
    private var symbolIsEmoji: Bool {
        guard let first = insight.symbol.unicodeScalars.first else { return false }
        return first.value > 127
    }

    var body: some View {
        HStack(alignment: .top, spacing: 12) {
            Group {
                if symbolIsEmoji {
                    Text(insight.symbol).font(.title2)
                } else {
                    Image(systemName: insight.symbol)
                        .font(.title2)
                        .foregroundStyle(insight.color)
                }
            }
            .frame(width: 40, height: 40)
            .background(Circle().fill(Brick.white))
            .overlay(Circle().stroke(Brick.ink, lineWidth: 2))

            VStack(alignment: .leading, spacing: 4) {
                Text(insight.title).font(.brickHeading(14)).foregroundStyle(Brick.ink)
                Text(insight.message).font(.brickBody(13)).foregroundStyle(Brick.ink.opacity(0.75))
            }
            Spacer()
        }
        .padding(14)
        .brickCard(fill: Brick.cream, cornerRadius: 16, borderWidth: 2.5, shadowOffset: 3.5)
    }
}

/// A small reusable brick card for top-level stats.
private struct BrickStatCard: View {
    let title: String
    let value: String
    let subtitle: String
    let symbol: String
    let tint: Color

    private var textColor: Color { tint.brickTextColor }

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            Label(title, systemImage: symbol)
                .font(.brickBodyHeavy(12))
                .foregroundStyle(textColor.opacity(0.9))
            Text(value)
                .font(.brickTitle(34))
                .foregroundStyle(textColor)
            Text(subtitle)
                .font(.brickBody(12))
                .foregroundStyle(textColor.opacity(0.8))
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .padding(16)
        .brickCard(fill: tint, cornerRadius: 18, borderWidth: 2.5, shadowOffset: 4)
        .overlay(BrickStuds(count: 3, diameter: 8, color: tint), alignment: .top)
    }
}

#Preview {
    NavigationStack {
        InsightsView()
    }
    .modelContainer(for: [Habit.self, HabitCompletion.self], inMemory: true)
}
